// ── Noto Emoji Data ──
// Static: https://fonts.gstatic.com/s/e/notoemoji/latest/{cp}/emoji.svg
// Animated (faces only): https://fonts.gstatic.com/s/e/notoemoji/latest/{cp}/512.gif

export interface EmojiEntry {
  emoji: string;
  name: string;
  /** hex codepoint(s) joined with _ for multi-codepoint sequences */
  cp: string;
  /** true if this emoji has an animated version (yellow faces only) */
  animated?: boolean;
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
}

function e(emoji: string, name: string, animated?: boolean): EmojiEntry {
  const cp = [...emoji].map((c) => c.codePointAt(0)!.toString(16)).join('_');
  return { emoji, name, cp, animated };
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'faces',
    label: 'Smileys',
    icon: '😊',
    emojis: [
      e('😀', 'grinning face', true),
      e('😃', 'grinning face with big eyes', true),
      e('😄', 'grinning face with smiling eyes', true),
      e('😁', 'beaming face', true),
      e('😆', 'grinning squinting face', true),
      e('😅', 'grinning face with sweat', true),
      e('🤣', 'rolling on the floor laughing', true),
      e('😂', 'face with tears of joy', true),
      e('🙂', 'slightly smiling face', true),
      e('🙃', 'upside-down face', true),
      e('🫠', 'melting face', true),
      e('😉', 'winking face', true),
      e('😊', 'smiling face with smiling eyes', true),
      e('😇', 'smiling face with halo', true),
      e('🥰', 'smiling face with hearts', true),
      e('😍', 'heart-eyes', true),
      e('🤩', 'star-struck', true),
      e('😘', 'face blowing a kiss', true),
      e('😗', 'kissing face', true),
      e('😚', 'kissing face with closed eyes', true),
      e('😙', 'kissing face with smiling eyes', true),
      e('🥲', 'smiling face with tear', true),
      e('😋', 'face savoring food', true),
      e('😛', 'face with tongue', true),
      e('😜', 'winking face with tongue', true),
      e('🤪', 'zany face', true),
      e('😝', 'squinting face with tongue', true),
      e('🤑', 'money-mouth face', true),
      e('🤗', 'hugging face', true),
      e('🤭', 'face with hand over mouth', true),
      e('🫢', 'face with open eyes & hand over mouth', true),
      e('🫣', 'face with peeking eye', true),
      e('🤫', 'shushing face', true),
      e('🤔', 'thinking face', true),
      e('🫡', 'saluting face', true),
      e('🤐', 'zipper-mouth face', true),
      e('🤨', 'face with raised eyebrow', true),
      e('😐', 'neutral face', true),
      e('😑', 'expressionless face', true),
      e('😶', 'face without mouth', true),
      e('🫥', 'dotted line face', true),
      e('😏', 'smirking face', true),
      e('😒', 'unamused face', true),
      e('🙄', 'face with rolling eyes', true),
      e('😬', 'grimacing face', true),
      e('🤥', 'lying face', true),
      e('🫨', 'shaking face', true),
      e('😌', 'relieved face', true),
      e('😔', 'pensive face', true),
      e('😪', 'sleepy face', true),
      e('🤤', 'drooling face', true),
      e('😴', 'sleeping face', true),
      e('😷', 'face with medical mask', true),
      e('🤒', 'face with thermometer', true),
      e('🤕', 'face with head-bandage', true),
      e('🤢', 'nauseated face', true),
      e('🤮', 'face vomiting', true),
      e('🥵', 'hot face', true),
      e('🥶', 'cold face', true),
      e('🥴', 'woozy face', true),
      e('😵', 'face with crossed-out eyes', true),
      e('🤯', 'exploding head', true),
      e('😎', 'smiling face with sunglasses', true),
      e('🥸', 'disguised face', true),
      e('🤓', 'nerd face', true),
      e('🧐', 'face with monocle', true),
      e('😕', 'confused face', true),
      e('🫤', 'face with diagonal mouth', true),
      e('😟', 'worried face', true),
      e('🙁', 'slightly frowning face', true),
      e('😮', 'face with open mouth', true),
      e('😯', 'hushed face', true),
      e('😲', 'astonished face', true),
      e('😳', 'flushed face', true),
      e('🥺', 'pleading face', true),
      e('🥹', 'face holding back tears', true),
      e('😦', 'frowning face with open mouth', true),
      e('😧', 'anguished face', true),
      e('😨', 'fearful face', true),
      e('😰', 'anxious face with sweat', true),
      e('😥', 'sad but relieved face', true),
      e('😢', 'crying face', true),
      e('😭', 'loudly crying face', true),
      e('😱', 'face screaming in fear', true),
      e('😖', 'confounded face', true),
      e('😣', 'persevering face', true),
      e('😞', 'disappointed face', true),
      e('😓', 'downcast face with sweat', true),
      e('😩', 'weary face', true),
      e('😫', 'tired face', true),
      e('🥱', 'yawning face', true),
      e('😤', 'face with steam from nose', true),
      e('😡', 'pouting face', true),
      e('😠', 'angry face', true),
      e('🤬', 'face with symbols on mouth', true),
      e('👿', 'angry face with horns', true),
      e('💀', 'skull'),
      e('💩', 'pile of poo', true),
      e('🤡', 'clown face', true),
      e('👹', 'ogre'),
      e('👺', 'goblin'),
      e('👻', 'ghost', true),
      e('👽', 'alien'),
      e('🤖', 'robot'),
    ],
  },
  {
    id: 'gestures',
    label: 'People',
    icon: '👋',
    emojis: [
      e('👋', 'waving hand'),
      e('🤚', 'raised back of hand'),
      e('🖐️', 'hand with fingers splayed'),
      e('✋', 'raised hand'),
      e('🖖', 'vulcan salute'),
      e('🫱', 'rightwards hand'),
      e('🫲', 'leftwards hand'),
      e('🫳', 'palm down hand'),
      e('🫴', 'palm up hand'),
      e('🫷', 'leftwards pushing hand'),
      e('🫸', 'rightwards pushing hand'),
      e('👌', 'OK hand'),
      e('🤌', 'pinched fingers'),
      e('🤏', 'pinching hand'),
      e('✌️', 'victory hand'),
      e('🤞', 'crossed fingers'),
      e('🫰', 'hand with index finger & thumb crossed'),
      e('🤟', 'love-you gesture'),
      e('🤘', 'sign of the horns'),
      e('🤙', 'call me hand'),
      e('👈', 'backhand index pointing left'),
      e('👉', 'backhand index pointing right'),
      e('👆', 'backhand index pointing up'),
      e('🖕', 'middle finger'),
      e('👇', 'backhand index pointing down'),
      e('☝️', 'index pointing up'),
      e('🫵', 'index pointing at the viewer'),
      e('👍', 'thumbs up'),
      e('👎', 'thumbs down'),
      e('✊', 'raised fist'),
      e('👊', 'oncoming fist'),
      e('🤛', 'left-facing fist'),
      e('🤜', 'right-facing fist'),
      e('👏', 'clapping hands'),
      e('🙌', 'raising hands'),
      e('🫶', 'heart hands'),
      e('👐', 'open hands'),
      e('🤲', 'palms up together'),
      e('🤝', 'handshake'),
      e('🙏', 'folded hands'),
      e('✍️', 'writing hand'),
      e('💪', 'flexed biceps'),
      e('🦾', 'mechanical arm'),
      e('🦿', 'mechanical leg'),
      e('👀', 'eyes'),
      e('👁️', 'eye'),
      e('👅', 'tongue'),
      e('👄', 'mouth'),
    ],
  },
  {
    id: 'hearts',
    label: 'Hearts & Symbols',
    icon: '❤️',
    emojis: [
      e('❤️', 'red heart'),
      e('🧡', 'orange heart'),
      e('💛', 'yellow heart'),
      e('💚', 'green heart'),
      e('💙', 'blue heart'),
      e('💜', 'purple heart'),
      e('🖤', 'black heart'),
      e('🤍', 'white heart'),
      e('🤎', 'brown heart'),
      e('💔', 'broken heart'),
      e('❤️‍🔥', 'heart on fire'),
      e('💕', 'two hearts'),
      e('💞', 'revolving hearts'),
      e('💓', 'beating heart'),
      e('💗', 'growing heart'),
      e('💖', 'sparkling heart'),
      e('💘', 'heart with arrow'),
      e('💝', 'heart with ribbon'),
      e('💟', 'heart decoration'),
      e('✨', 'sparkles'),
      e('⭐', 'star'),
      e('🌟', 'glowing star'),
      e('💫', 'dizzy'),
      e('🔥', 'fire'),
      e('💥', 'collision'),
      e('💢', 'anger symbol'),
      e('💦', 'sweat droplets'),
      e('💨', 'dashing away'),
      e('🕳️', 'hole'),
      e('💣', 'bomb'),
      e('💬', 'speech balloon'),
      e('👁️‍🗨️', 'eye in speech bubble'),
      e('💤', 'zzz'),
      e('✅', 'check mark'),
      e('❌', 'cross mark'),
      e('❓', 'question mark'),
      e('❗', 'exclamation mark'),
      e('💯', 'hundred points'),
      e('🏳️', 'white flag'),
      e('🏴', 'black flag'),
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    icon: '🌿',
    emojis: [
      e('🐶', 'dog face'),
      e('🐱', 'cat face'),
      e('🐭', 'mouse face'),
      e('🐹', 'hamster'),
      e('🐰', 'rabbit face'),
      e('🦊', 'fox'),
      e('🐻', 'bear'),
      e('🐼', 'panda'),
      e('🐻‍❄️', 'polar bear'),
      e('🐨', 'koala'),
      e('🐯', 'tiger face'),
      e('🦁', 'lion'),
      e('🐮', 'cow face'),
      e('🐷', 'pig face'),
      e('🐸', 'frog'),
      e('🐵', 'monkey face'),
      e('🙈', 'see-no-evil monkey'),
      e('🙉', 'hear-no-evil monkey'),
      e('🙊', 'speak-no-evil monkey'),
      e('🐔', 'chicken'),
      e('🐧', 'penguin'),
      e('🐦', 'bird'),
      e('🦅', 'eagle'),
      e('🦉', 'owl'),
      e('🦇', 'bat'),
      e('🐺', 'wolf'),
      e('🐗', 'boar'),
      e('🐴', 'horse face'),
      e('🦄', 'unicorn'),
      e('🐝', 'honeybee'),
      e('🪱', 'worm'),
      e('🐛', 'bug'),
      e('🦋', 'butterfly'),
      e('🐌', 'snail'),
      e('🐞', 'lady beetle'),
      e('🐢', 'turtle'),
      e('🐍', 'snake'),
      e('🦎', 'lizard'),
      e('🐙', 'octopus'),
      e('🦑', 'squid'),
      e('🦀', 'crab'),
      e('🐠', 'tropical fish'),
      e('🐟', 'fish'),
      e('🐬', 'dolphin'),
      e('🐳', 'spouting whale'),
      e('🦈', 'shark'),
      e('🌸', 'cherry blossom'),
      e('🌹', 'rose'),
      e('🌺', 'hibiscus'),
      e('🌻', 'sunflower'),
      e('🌿', 'herb'),
      e('🍀', 'four leaf clover'),
      e('🍁', 'maple leaf'),
      e('🍂', 'fallen leaf'),
      e('🌾', 'sheaf of rice'),
      e('🌵', 'cactus'),
      e('🌲', 'evergreen tree'),
      e('🌳', 'deciduous tree'),
      e('🪨', 'rock'),
      e('🍄', 'mushroom'),
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    icon: '🍕',
    emojis: [
      e('🍎', 'red apple'),
      e('🍊', 'tangerine'),
      e('🍋', 'lemon'),
      e('🍌', 'banana'),
      e('🍉', 'watermelon'),
      e('🍇', 'grapes'),
      e('🍓', 'strawberry'),
      e('🫐', 'blueberries'),
      e('🍑', 'peach'),
      e('🥭', 'mango'),
      e('🍍', 'pineapple'),
      e('🥥', 'coconut'),
      e('🥝', 'kiwi'),
      e('🍅', 'tomato'),
      e('🥑', 'avocado'),
      e('🌽', 'ear of corn'),
      e('🌶️', 'hot pepper'),
      e('🥒', 'cucumber'),
      e('🥦', 'broccoli'),
      e('🧄', 'garlic'),
      e('🥔', 'potato'),
      e('🍞', 'bread'),
      e('🥐', 'croissant'),
      e('🍕', 'pizza'),
      e('🌮', 'taco'),
      e('🌯', 'burrito'),
      e('🍔', 'hamburger'),
      e('🍟', 'french fries'),
      e('🌭', 'hot dog'),
      e('🍿', 'popcorn'),
      e('🧀', 'cheese'),
      e('🥚', 'egg'),
      e('🍳', 'cooking'),
      e('🥓', 'bacon'),
      e('🍗', 'poultry leg'),
      e('🍖', 'meat on bone'),
      e('🍣', 'sushi'),
      e('🍜', 'steaming bowl'),
      e('🍝', 'spaghetti'),
      e('🍰', 'shortcake'),
      e('🎂', 'birthday cake'),
      e('🍩', 'doughnut'),
      e('🍪', 'cookie'),
      e('🍫', 'chocolate bar'),
      e('🍬', 'candy'),
      e('☕', 'hot beverage'),
      e('🍵', 'teacup'),
      e('🧃', 'beverage box'),
      e('🥤', 'cup with straw'),
      e('🍺', 'beer mug'),
      e('🍻', 'clinking beer mugs'),
      e('🥂', 'clinking glasses'),
      e('🍷', 'wine glass'),
      e('🍸', 'cocktail glass'),
      e('🧊', 'ice'),
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    icon: '🎉',
    emojis: [
      e('⚽', 'soccer ball'),
      e('🏀', 'basketball'),
      e('🏈', 'american football'),
      e('⚾', 'baseball'),
      e('🎾', 'tennis'),
      e('🏐', 'volleyball'),
      e('🏉', 'rugby football'),
      e('🎱', 'pool 8 ball'),
      e('🏓', 'ping pong'),
      e('🏒', 'ice hockey'),
      e('🥊', 'boxing glove'),
      e('🎯', 'bullseye'),
      e('⛳', 'flag in hole'),
      e('🎮', 'video game'),
      e('🕹️', 'joystick'),
      e('🎲', 'game die'),
      e('🧩', 'puzzle piece'),
      e('🎭', 'performing arts'),
      e('🎨', 'artist palette'),
      e('🎬', 'clapper board'),
      e('🎤', 'microphone'),
      e('🎧', 'headphone'),
      e('🎵', 'musical note'),
      e('🎶', 'musical notes'),
      e('🎹', 'musical keyboard'),
      e('🎸', 'guitar'),
      e('🥁', 'drum'),
      e('🎺', 'trumpet'),
      e('🎷', 'saxophone'),
      e('🪗', 'accordion'),
      e('🎻', 'violin'),
      e('🎪', 'circus tent'),
      e('🎉', 'party popper'),
      e('🎊', 'confetti ball'),
      e('🎈', 'balloon'),
      e('🎁', 'wrapped gift'),
      e('🎀', 'ribbon'),
      e('🏆', 'trophy'),
      e('🥇', 'gold medal'),
      e('🥈', 'silver medal'),
      e('🥉', 'bronze medal'),
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      e('💡', 'light bulb'),
      e('🔦', 'flashlight'),
      e('🕯️', 'candle'),
      e('📱', 'mobile phone'),
      e('💻', 'laptop'),
      e('🖥️', 'desktop computer'),
      e('⌨️', 'keyboard'),
      e('🖱️', 'computer mouse'),
      e('🖨️', 'printer'),
      e('📷', 'camera'),
      e('📹', 'video camera'),
      e('📺', 'television'),
      e('📻', 'radio'),
      e('🔔', 'bell'),
      e('🔕', 'bell with slash'),
      e('📢', 'loudspeaker'),
      e('📣', 'megaphone'),
      e('🔑', 'key'),
      e('🗝️', 'old key'),
      e('🔒', 'locked'),
      e('🔓', 'unlocked'),
      e('🔐', 'locked with key'),
      e('🛡️', 'shield'),
      e('🔧', 'wrench'),
      e('🔨', 'hammer'),
      e('⚙️', 'gear'),
      e('🧲', 'magnet'),
      e('🧪', 'test tube'),
      e('🧬', 'dna'),
      e('🔬', 'microscope'),
      e('🔭', 'telescope'),
      e('📡', 'satellite antenna'),
      e('💉', 'syringe'),
      e('💊', 'pill'),
      e('🩹', 'adhesive bandage'),
      e('📦', 'package'),
      e('📎', 'paperclip'),
      e('📌', 'pushpin'),
      e('✏️', 'pencil'),
      e('📝', 'memo'),
      e('📚', 'books'),
      e('📖', 'open book'),
      e('🗂️', 'card index dividers'),
      e('📁', 'file folder'),
      e('🗑️', 'wastebasket'),
      e('⏰', 'alarm clock'),
      e('⌛', 'hourglass done'),
      e('⏳', 'hourglass not done'),
    ],
  },
  {
    id: 'flags',
    label: 'Flags & Travel',
    icon: '🚀',
    emojis: [
      e('🚀', 'rocket'),
      e('✈️', 'airplane'),
      e('🚗', 'automobile'),
      e('🚕', 'taxi'),
      e('🚌', 'bus'),
      e('🚂', 'locomotive'),
      e('🚢', 'ship'),
      e('🛸', 'flying saucer'),
      e('🚁', 'helicopter'),
      e('🏠', 'house'),
      e('🏢', 'office building'),
      e('🏥', 'hospital'),
      e('🏫', 'school'),
      e('🏰', 'castle'),
      e('⛪', 'church'),
      e('🗽', 'statue of liberty'),
      e('🗼', 'Tokyo tower'),
      e('🌍', 'globe Europe-Africa'),
      e('🌎', 'globe Americas'),
      e('🌏', 'globe Asia-Australia'),
      e('🌙', 'crescent moon'),
      e('🌛', 'first quarter moon face'),
      e('⭐', 'star'),
      e('🌈', 'rainbow'),
      e('☀️', 'sun'),
      e('🌤️', 'sun behind small cloud'),
      e('⛅', 'sun behind cloud'),
      e('🌧️', 'cloud with rain'),
      e('⛈️', 'cloud with lightning & rain'),
      e('🌩️', 'cloud with lightning'),
      e('❄️', 'snowflake'),
      e('☃️', 'snowman'),
      e('🌊', 'water wave'),
    ],
  },
];

/** All emojis in a flat list */
export const ALL_EMOJIS = EMOJI_CATEGORIES.flatMap((c) => c.emojis);

/** Quick lookup by emoji character */
const EMOJI_MAP = new Map<string, EmojiEntry>();
for (const entry of ALL_EMOJIS) EMOJI_MAP.set(entry.emoji, entry);

export function getEmojiEntry(emoji: string): EmojiEntry | undefined {
  return EMOJI_MAP.get(emoji);
}

/** Get the Noto static SVG URL for an emoji */
export function getNotoUrl(entry: EmojiEntry): string {
  return `https://fonts.gstatic.com/s/e/notoemoji/latest/${entry.cp}/emoji.svg`;
}

/** Get the Noto animated GIF URL for a face emoji */
export function getNotoAnimatedUrl(entry: EmojiEntry): string {
  return `https://fonts.gstatic.com/s/e/notoemoji/latest/${entry.cp}/512.gif`;
}

/** Recently used emojis — stored in localStorage */
const RECENT_KEY = 'emoji_recent';
const MAX_RECENT = 24;

export function getRecentEmojis(): string[] {
  try {
    return JSON.parse(localStorage.getItem(RECENT_KEY) || '[]');
  } catch { return []; }
}

export function addRecentEmoji(emoji: string): void {
  const recent = getRecentEmojis().filter((e) => e !== emoji);
  recent.unshift(emoji);
  if (recent.length > MAX_RECENT) recent.length = MAX_RECENT;
  localStorage.setItem(RECENT_KEY, JSON.stringify(recent));
}

/** Favorite emojis — stored in localStorage */
const FAVORITES_KEY = 'emoji_favorites';

export function getFavoriteEmojis(): string[] {
  try {
    return JSON.parse(localStorage.getItem(FAVORITES_KEY) || '[]');
  } catch { return []; }
}

export function toggleFavoriteEmoji(emoji: string): boolean {
  const favs = getFavoriteEmojis();
  const idx = favs.indexOf(emoji);
  if (idx >= 0) {
    favs.splice(idx, 1);
    localStorage.setItem(FAVORITES_KEY, JSON.stringify(favs));
    return false;
  } else {
    favs.push(emoji);
    localStorage.setItem(FAVORITES_KEY, JSON.stringify(favs));
    return true;
  }
}

export function isFavoriteEmoji(emoji: string): boolean {
  return getFavoriteEmojis().includes(emoji);
}
